### ISSUE TITLE
Make it work in VISUAL mode

### ISSUE THREAD

**Issue by astyagun** [haya14busa/vim-edgemotion#2]
I have these mappings setup:

```viml
map ]g <Plug>(edgemotion-j)
map [g <Plug>(edgemotion-k)
```

Steps:
* `{V]g`

Expected:
* Block of text to become selected

Result:
* Cursor jumps to the end of the block of text losing the selection

**Comment by haya14busa** [comment]
Thank you for the report.

I fixed it https://github.com/haya14busa/vim-edgemotion/commit/c9b181733e6190af6964753728c25bfee1cbd941
