### ISSUE TITLE
Add note to suggested mappings about incompatibility with vim-tmux-navigator

### ISSUE THREAD

**Issue by kiryph** [haya14busa/vim-edgemotion#6]
For a vim user finding the right key mapping for additional features can be challenging.
Therefore, I think vim plugins should suggest at least one good choice which IMHO `<C-j>` and `<C-k>` actually are.

However, they can overwrite typically unused builtins or interfere with other plugins. This could be noted. IMHO in this case a note about an incompatibility with

- https://github.com/christoomey/vim-tmux-navigator
  (2.2k stars and 5.4k user according to vimawesome)

would be worthwhile.

**UPDATE**
For comparison, the plugin https://github.com/vim-utils/vim-vertical-move uses `[v` and `]v` which, however, are not as convenient as `<C-j>` and `<C-k>`.

**Comment by haya14busa** [comment]
I cannot handle all popular plugins mappings and I expect users to find on their own mapping.

**Comment by kiryph** [comment]
I did not mean to add a comprehensive list of (popular) plugins which also use these mappings.

I had a sentence like

> Note, `<C-j>` and `<C-k>` are only suggestions which might interfere with your custom keybindings (e.g. when following the suggestion from [vim wikia](http://vim.wikia.com/wiki/Switch_between_Vim_window_splits_easily#Ctrl.2Bkjhl_Navigation) to switch vim windows more easily) or might be used by other plugins (e.g. [vim-tmux-navigator](https://github.com/christoomey/vim-tmux-navigator)).

in mind.

`<C-j>` and `<C-k>` are key mappings which are actually quite precious because there are not many left with this level of convenience. Using the `<Alt>` key does not work in all environments. Afaik the mappings under discussion have often been suggested to navigate through vim windows, tmux panes and window manager splits (e.g. ratpoison):

- http://silly-bytes.blogspot.com/2016/06/seamlessly-vim-tmux-windowmanager_24.html
- https://robots.thoughtbot.com/vim-splits-move-faster-and-more-naturally
- https://nvie.com/posts/how-i-boosted-my-vim/#get-efficient-shortcut-mappings
- https://github.com/zhamlin/tiler.vim/blob/master/doc/tiler.txt#L232-L236
- https://www.reddit.com/r/vim/comments/6h3k82/do_you_recommend_this_simple_keymap_for_window/


Therefore reminding user about this emphasizes immediately if a user has to search for new mappings when they want to use your plugin for their current setup.

**Update**
Just to mention **only here** another plugin which uses them for switching vim windows:

- https://github.com/spolu/dwm.vim (600 stars) `<C-j>` and `<C-k>`

**Comment by kiryph** [comment]
## Personal note about own plugin mappings

I prefer plugins which provide strong default keybindings I can live with. These are e.g. 
- vim-surround `ys` `cs` `ds`,
- vim-unimpaired `yo`+ letter to toggle options and many `[`-mappings e.g. `[<Space>` `[e`,
- vim-commentary `gc`,
- vim-exchange `cx`,
- vim-lion `gl`,
- [vim-dispatch](https://github.com/tpope/vim-dispatch/blob/master/doc/dispatch.txt#L128-L147) e.g. `m<Cr>`,
- vim-abolish `cr`
- vim-scriptease `g=`, `zS`
- vim-vinegar `-`

This means these plugins can become more easily default plugins:
- see for example the project [Oni](https://github.com/onivim/oni#bundled-plugins) (unimpaired, commentary, surround) or
- plugins in the debian package [vim-scripts](https://packages.debian.org/stretch/all/vim-scripts/filelist).

They can also be used for admin accounts on shared machines or for paired-programming sessions. You can use them in a vim setup of a colleague when helping him.

Otherwise this is not possible.

Another thought is: 
Leaving it to the user is a valid strategy but providing default mappings shows a way how a plugin fits into the existing vim eco world. And if you care: this helps to spread your plugin to get more stars 😀 .

**Comment by kiryph** [comment]
## Alternative Key Mappings Compatible with `vim-tmux-navigator`

If someone ends up in this issue who wants to use vim-tmux-navigator as it is and edgemotion, you can consider following options

1) `g{` and `g}`
    modified `{` and `}`
    ```viml
    map g{ <Plug>(edgemotion-k)
    map g} <Plug>(edgemotion-j)
    ```

2) `[v` and `]v`
    stolen from https://github.com/vim-utils/vim-vertical-move

    ```viml
    map [v <Plug>(edgemotion-k)
    map ]v <Plug>(edgemotion-j)
    ```

3) `gk` and `gj` (changes default mappings)
    ```viml
    nnoremap <expr> k v:count ? 'k' : 'gk'
    nnoremap <expr> j v:count ? 'j' : 'gj'
    map gk <Plug>(edgemotion-k)
    map gj <Plug>(edgemotion-j)
    ```

**Comment by haya14busa** [comment]
what if another popular plugin uses `g{`? 

Showing alternative mappings doesn't solve anything.

**Comment by haya14busa** [comment]
> Another thought is:
Leaving it to the user is a valid strategy but providing default mappings shows a way how a plugin fits into the existing vim eco world. And if you care: this helps to spread your plugin to get more stars 😀 .

I think it's better to help users know how to define mappings and choose good mappings for their own instead of writing alternative mappings in each plugin document.
(e.g. writing blog posts, improving vim document, etc..)

**Comment by kiryph** [comment]
> what if another popular plugin uses g{?

I do not know any plugin which uses `g{`. If you **immediately** know one, I would really be happy if you can point this out. If it is a mainstream plugin which has a larger user base, I would agree it would be a bad choice. There are plugins which are recommended to extend vim in a useful and friendly way. For example see https://www.vi-improved.org/plugins/ who define what a good vim citizen (plugin) is:

> "Do no harm" plugins don't break core Vim features and play nice with other plugins (try not to conflict with keybindings, etc) and respect your settings and colorscheme.

> Showing alternative mappings doesn't solve anything.

Well, using `g{` and `g}` allows you to use both plugins at the same time. I would argue that solves the issue I referred to with my initial request. For instance, I did not suggest to use `<Alt-j>` because it might not work for everyone. And I added a note to my third suggestion that this changes builtin mappings.

> I think it's better to help users know how to define mappings and choose good mappings for their own instead of writing alternative mappings in each plugin document.
(e.g. writing blog posts, improving vim document, etc..)

You are certainly right about this. However, you mention *choose good mappings for their own* which is actually more difficult in my experience than you imply. I think someone who already uses your suggested mappings for something else has to search on his own for new mapppings. There is no help.

Not everyone is completely familiar with all the default mappings of vim and possible plugins in use.
Therefore providing useful suggestions can actually be helpful and reduce time someone invests in learning new mappings which turn out to be a bad choice.

A personal experience: I used the bad recommendation to use `,` as a leader key which is actual a useful motion. It took me some time to look for a new leader key and actually using `,` as intended.

There is a reason why people do not remap the vast majority of keys and use the default bindings.

BTW I did not suggest to add the alternatives to the README.md. I think you got me wrong here.

The only thing I asked about was making the user aware of a known compatibility issue which I consider not too obscure.

**Comment by kiryph** [comment]
And before we continue our discussion: From my point of view this issue is closed. I actually do not try to convince you of anything. I just wanted to explain why I raised this issue and to reply to your question.
